### ISSUE TITLE
ブログ作ったし次何つくろうか

### ISSUE THREAD

**Issue by 92thunder** [TNCT-SYSKEN/RailsTraining#5]
どうしましょ

**Comment by asonas** [comment]
ブログを拡張するというのもいいのかな？
僕がRails寺子屋でよくやってたのは、

* はてなスターのようなVoteできる
* マークダウンがかける
* 写真の投稿ができる

というような機能があります。
上から、

* データモデルについての応用
* ControllerとViewの復習
 * markdownのパースは自力でやるのはつらいので下のgemがおすすめです
 * https://github.com/increments/qiita-markdown
* gem を使った外部コンテンツを扱う方法

という目的があってそれなりに実践的な内容にもなります。

**Comment by 92thunder** [comment]
そのマークダウンがパースできるgemおもしろそうですね！
ではブログの拡張をもう少し進めていきます。

**Comment by 92thunder** [comment]
結局今年２回しかする時間がなかったので僕が夏休みに作ったアプリを作ることにしました

結局基礎だけしか教えれてませんが、基礎を教えれただけでも良しとしようと思います。

**Comment by asonas** [comment]
:sparkles:
